### ISSUE TITLE
Service endpoints and metrics configuration

### ISSUE THREAD

**Issue by denisacostaq** [simelo/rextporter#2]
- [x] path(s) to monitor
- [x] format (JSON)
- [x] auth plugin (Skycoin CSRF)
- [x] type of metrics at endpoint
- [x] metrics (meta)data (name, type, boundary values, ...) and how to extract them from endpoint response data (XPath , JsonPath).
- [x] Services types matching description
- [x] Explained in README

**Comment by olemis** [comment]
code fixing this already in `develop`
